### ISSUE TITLE
Add an onAnimationFinished Listener

### ISSUE THREAD

**Issue by THMCombine** [skymansandy/typewriterview#1]
Hello,

Would it be possible to add an onAnimationFinished listener? It would allow me to further animate other views based on when this is done typing.

**Comment by skymansandy** [comment]
Hi,

Cool, I'll add the listener and release an update soon :)
Thanks for suggestion.

**Comment by THMCombine** [comment]
Nice, I'll be looking forward to your update!

**Comment by skymansandy** [comment]
Hey,
Sorry for not being able to work on this for a while now, Added the necessary listeners. Have a look!
Thanks for the suggestion :)
